name: Build & Deploy (Stage)

on:
  push:
    branches: [stage]

  workflow_dispatch:

jobs:
  build:
    name: Build (Stage)
    runs-on: self-hosted

    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        id: build_step
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/seventv/servergo/stage:${{ github.sha }}
            ghcr.io/seventv/servergo/stage:latest

  deploy:
    name: Deploy (Stage)
    runs-on: self-hosted
    needs: # Run this after build
      - build

    steps:
        # Checkout repository
        - uses: actions/checkout@v2

        # Deploy to k8s
        - name: Install kubectl&
          uses: azure/setup-kubectl@v1

        - name: Apply Deployment & Rollout
          env:
            KUBE_CONFIG_DATA: ${{ secrets.K8S_CONFIG }}
            KUBE_RESOURCE: statefulsets
            KUBE_IMAGE_PATCH: >-
              [
                { "op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "ghcr.io/seventv/servergo/stage:${{ github.sha }}" }
              ]
          run: |
            mkdir -p ~/.kube
            (echo $KUBE_CONFIG_DATA | base64 -d) >> ~/.kube/config
            kubectl config use-context 7tv-as-deployer

            kubectl apply -f k8s/stage.yaml
            kubectl patch $KUBE_RESOURCE 7tv-stageapi --type="json" -p="$KUBE_IMAGE_PATCH"

            kubectl rollout restart -n 7tv sts/7tv-stageapi
